name: ${project.name}
main: li.cryx.expcraft.digging.Digging
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Digging level for ExpCraft.

permissions:
  ec.module.d:
    description: Enable Digging module
    default: true
