# Default EC-Mining config file
PickaxeLevel:
  Wooden: 0
  Stone: 5
  Iron: 10
  Gold: 20
  Diamond: 30

ExpGain:
  Stone: 5.0
  Cobble: 5.0
  Redstone: 20.0
  GoldOre: 30.0
  IronOre: 20.0
  CoalOre: 10.0
  LapisOre: 100.0
  MossStone: 10.0
  Obsidian: 200.0
  DiamondOre: 100.0
  Netherrack: 3.0
  SandStone: 3.0

UseLevel:
  Stone: 0
  Cobble: 0
  Redstone: 10
  GoldOre: 20
  IronOre: 5
  CoalOre: 5
  LapisOre: 20
  MossStone: 0
  Obsidian: 35
  DiamondOre: 25
  Netherrack: 0
  SandStone: 0
