name: ${project.name}
main: li.cryx.expcraft.mining.Mining
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Mining Level for ExpCraft.

permissions:
  ec.module.m:
    description: Enable Mining module
    default: true
