name: ${project.name}
main: li.cryx.expcraft.dexterity.Dexterity
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Dexterity Level for ExpCraft.
commands:

permissions:
  ec.module.dx:
    description: Enable Dexterity module
    default: true
