name: ${project.name}
main: li.cryx.expcraft.farming.Farming
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Farming Level for ExpCraftCore.
commands:

