# Default EC-WoodCutting config file
AxeLevel:
  Wooden: 0
  Stone: 5
  Iron: 10
  Gold: 20
  Diamond: 30

ExpGain:
  Log: 5.0
  Plank: 2.0
  Leaves: 0.1
  Fence: 1.0

UseLevel:
  Redwood: 0
  Birch: 0
  Log: 0
  Plank: 0
  Fence: 0

Settings:
  EnableDoubleDrop: true
  DropMultiplier: 1.0
