name: ${project.name}
main: li.cryx.expcraft.woodcutting.WoodCutting
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The WoodCutting Level for LevelCraftCore.
commands:

permissions:
  ec.module.w:
    description: Enable WoodCutting module
    default: true
