# Default EC-Alchemy config file
ExpGain:
  Default: 1.0

Recipe:
# turn sand into cobblestone
- shape: SHAPELESS
  output: COBBLESTONE;;2
  input:
  - SAND;;2
  level: 0
  exp: 1.0
# turn cobblestone into sand
- shape: SHAPELESS
  output: SAND;;2
  input:
  - COBBLESTONE;;2
  level: 0
  exp: 1.0
# mix sand and cobblestone into dirt
- shape: SHAPELESS
  output: DIRT;;2
  input:
  - SAND;;1
  - COBBLESTONE;;1
  level: 0
  exp: 1.0
# mix sand and dirt into cobblestone
- shape: SHAPELESS
  output: COBBLESTONE;;2
  input:
  - SAND;;1
  - DIRT;;1
  level: 0
  exp: 1.0
# mix cobblestone and dirt into sand
- shape: SHAPELESS
  output: SAND;;2
  input:
  - COBBLESTONE;;1
  - DIRT;;1
  level: 0
  exp: 1.0
# turn two half-slabs into their respective block
- shape: SHAPED
  output: COBBLESTONE;;1
  input:
  - STEP;3;1
  - STEP;3;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: 45;;1
  input:
  - STEP;4;1
  - STEP;4;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: 98;;1
  input:
  - STEP;5;1
  - STEP;5;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: STONE;;1
  input:
  - STEP;0;1
  - STEP;0;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: WOOD;0;1
  input:
  - WOOD_STEP;0;1
  - WOOD_STEP;0;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: WOOD;1;1
  input:
  - WOOD_STEP;1;1
  - WOOD_STEP;1;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: WOOD;2;1
  input:
  - WOOD_STEP;2;1
  - WOOD_STEP;2;1
  level: 0
  exp: 1.0
- shape: SHAPED
  output: WOOD;3;1
  input:
  - WOOD_STEP;3;1
  - WOOD_STEP;3;1
  level: 0
  exp: 1.0
# turn sandstone into sand
- shape: SHAPELESS
  output: SAND;;4
  input: 
  - SANDSTONE;;1
  level: 0
  exp: 1.0
# smelt buckets into iron ingots
- shape: FURNACE
  output: IRON_INGOT;;3
  input: BUCKET;;1
# alter gold and rotten flesh into blaze rod
- shape: SHAPED
  output: BLAZE_ROD;;1
  input:
  - ROTTEN_FLESH;;1,ROTTEN_FLESH;;1,ROTTEN_FLESH;;1
  - ROTTEN_FLESH;;1,GOLD_INGOT;;1,ROTTEN_FLESH;;1
  - ROTTEN_FLESH;;1,ROTTEN_FLESH;;1,ROTTEN_FLESH;;1
  level: 5
  exp: 0.1
# craft chainmail armour from stone
- shape: SHAPED
  output: CHAINMAIL_HELMET;;1
  input:
  - STONE;;1,STONE;;1,STONE;;1
  - STONE;;1,AIR;;1,STONE;;1
  level: 10
  exp: 5.0
- shape: SHAPED
  output: CHAINMAIL_CHESTPLATE;;1
  input:
  - STONE;;1,AIR;;1,STONE;;1
  - STONE;;1,STONE;;1,STONE;;1
  - STONE;;1,STONE;;1,STONE;;1
  level: 10
  exp: 8.0
- shape: SHAPED
  output: CHAINMAIL_LEGGINGS;;1
  input:
  - STONE;;1,STONE;;1,STONE;;1
  - STONE;;1,AIR;;1,STONE;;1
  - STONE;;1,AIR;;1,STONE;;1
  level: 10
  exp: 7.0
- shape: SHAPED
  output: CHAINMAIL_BOOTS;;1
  input:
  - STONE;;1,AIR;;1,STONE;;1
  - STONE;;1,AIR;;1,STONE;;1
  level: 10
  exp: 4.0
# turn saddles into leather
- shape: SHAPELESS
  output: LEATHER;;1
  input: 
  - SADDLE;;1
  level: 0
  exp: 1.0
