#Default ExpCraftCore config file
Colors:
  ColourOne: GOLD
  ColourTwo: YELLOW
  ColourGood: GREEN
  ColourBad: RED

Database: FlatFile
DbConnection:
  URL: localhost:3306/minecraft
  User: root
  Password: pass

Levels:
  Constant: 20
  LevelCap: 100
