#Default ExpCraftCore config file
Chat:
  PlayLevelUpSound: true
  NotifyAll: true

Colors:
  ColorOne: GOLD
  ColorTwo: YELLOW
  ColorGood: GREEN
  ColorBad: RED

Database: FlatFile

Levels:
  Constant: 20
  LevelCap: 100
