#Default ExpCraftCore config file
Colors:
  ColorOne: GOLD
  ColorTwo: YELLOW
  ColorGood: GREEN
  ColorBad: RED

Database: FlatFile
DbConnection:
  URL: localhost:3306/minecraft
  User: root
  Password: pass

Levels:
  Constant: 20
  LevelCap: 100
