name: ${project.name}

main: li.cryx.expcraft.ExpCraftCore
version: ${project.version}
description: >
             Commands for use with the ${project.name} experience-based plugin for Minecraft.

commands:
  level:
    description: Returns information about a player's experience and levels.
    usage:
  lvl:
    description: Returns information about a player's experience and levels.
    usage: