name: ${project.name}
main: TODO fully qualified class name of your ExpCraftModule
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Template Level for ExpCraft. TODO change this

# TODO set the permission node for the module
# must have the format "ec.module." plus your module's abbreviation
permissions:
  ec.module.t:
    description: Enable Template module
    default: true
