name: ${project.name}
main: li.cryx.expcraft.defence.Defence
version: ${project.version}
depend: [ExpCraftCore]
description: >
             ${project.name}. The Defence Level for ExpCraft.

permissions:
  ec.module.de:
    description: Enable Defence module
    default: true
